//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_UploadAssignment
    {
        public int Upload_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Upload_Dt { get; set; }
        public string FileName { get; set; }
    }
}
