//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_uploadstudyMaterial
    {
        public int Material_id { get; set; }
        public string Subject { get; set; }
        public string title { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string Upload_DT { get; set; }
    }
}
