//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Notification
    {
        public int Notification_Id { get; set; }
        public string Noti_Message { get; set; }
        public string Noti_DT { get; set; }
    }
}
