//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback_Tbl
    {
        public int Feedback_Id { get; set; }
        public string Topic { get; set; }
        public string Message { get; set; }
        public string UserId { get; set; }
        public string Feedback_DT { get; set; }
    
        public virtual Feedback_Tbl Feedback_Tbl1 { get; set; }
        public virtual Feedback_Tbl Feedback_Tbl2 { get; set; }
        public virtual Registration_Master Registration_Master { get; set; }
    }
}
