//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_education.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationDBEntities : DbContext
    {
        public EducationDBEntities()
            : base("name=EducationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feedback_Tbl> Feedback_Tbl { get; set; }
        public virtual DbSet<Registration_Master> Registration_Master { get; set; }
        public virtual DbSet<Tbl_Notification> Tbl_Notification { get; set; }
        public virtual DbSet<Tbl_uploadAssignment> Tbl_uploadAssignment { get; set; }
        public virtual DbSet<Tbl_Login> Tbl_Login { get; set; }
        public virtual DbSet<Tbl_uploadstudyMaterial> Tbl_uploadstudyMaterial { get; set; }
        public virtual DbSet<Tbl_Enquiry> Tbl_Enquiry { get; set; }
        public virtual DbSet<Admin_UploadAssignment> Admin_UploadAssignment { get; set; }
    }
}
