//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration_Master()
        {
            this.Feedback_Tbl = new HashSet<Feedback_Tbl>();
        }
    
        public string Email_id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string College { get; set; }
        public string Year { get; set; }
        public string Course { get; set; }
        public string Mobile_No { get; set; }
        public string pic_Upload { get; set; }
        public string DOB { get; set; }
        public string Address { get; set; }
        public string Pass { get; set; }
        public string Registered_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback_Tbl> Feedback_Tbl { get; set; }
    }
}
